repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: name-tests-test
        args: ["--pytest-test-first"]
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.15.9"
    hooks:
      - id: ruff-check
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/adamchainz/blacken-docs
    rev: "1.19.1"
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==24.*]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.19.1"
    hooks:
      - id: mypy
        files: src/thztools|tests
        args:
          [
            --strict,
            --ignore-missing-imports,
            --warn-unreachable,
            --show-error-code-links,
            --show-error-context,
          ]
        additional_dependencies: [numpy, pytest, scipy-stubs]
        verbose: true
  - repo: https://github.com/codespell-project/codespell
    rev: "v2.4.2"
    hooks:
      - id: codespell
  #        args: ["-L", "ois"]
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: "v1.10.0"
    hooks:
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: "v3.8.1"
    hooks:
      - id: prettier
        types_or: [yaml, markdown, html, css, scss, javascript, json]
ci:
  autoupdate_commit_msg: "chore: update pre-commit hooks"
