name: Documentation
description: Report an issue related to the THzTools documentation.
title: "DOC: <Please write a comprehensive title after the 'DOC: ' prefix>"
labels: [Documentation]

body:
- type: textarea
  attributes:
    label: "Issue with current documentation:"
    description: >
      Please link to the document/code you're referring to at
      https://dodge-research-group.github.io/thztools/.

- type: textarea
  attributes:
    label: "Idea or request for content:"
    description: >
      Please describe as clearly as possible a suggested fix, better phrasing or
      topics you think are missing from the current documentation.

- type: textarea
  attributes:
    label: Additional context (e.g. screenshots, GIFs)